---
- name: Provision EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    instance_count: 2
    region: "us-east-1"
    ami_id: "ami-0440d3b780d96b29d" # Amazon Linux 2023
    instance_type: "t3.micro"
  
  tasks:
    - name: setup sg for the ec2_instance
      amazon.aws.ec2_security_group:
        name: "friday-sg"
        description: "Security group for Ansible provisioned EC2 instances"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp            
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: sg_result

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "my-ec2-instance-{{item}}"
        key_name: "ansible-key"
        instance_type: "{{instance_type}}"
        image_id: "{{ami_id}}"
        region: "{{region}}"
        vpc_subnet_id: "subnet-016c0eff1f1e1f785"
        security_group: "{{ sg_result.group_id }}"
        wait: yes
      loop: "{{ range(1, instance_count + 1) | list }}"
      register: ec2_instance
    
    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groups: "new_servers"
      loop: "{{ ec2_instance.results | map(attribute='instances') | flatten }}"

# --- SECOND PLAY: CONFIGURATION ---
- name: Configure new servers
  hosts: new_servers
  gather_facts: yes
  # Note: Do not put 'become: yes' at this top level 
  # to avoid the "sudo not found" error during the initial handshake.

  tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300
    - name: Force Install Sudo and Python (Bootstrap)
      # This sends a direct command as the 'ec2-user' or 'ubuntu' user
      ansible.builtin.raw: |
        (command -v sudo >/dev/null 2>&1) || (yum install -y sudo || apt-get update && apt-get install -y sudo)
      changed_when: true

    - name: Install Apache (HTTPD for Amazon Linux)
      ansible.builtin.yum:
        name: httpd
        state: present
      become: yes # Only become root for the actual install

    - name: Start Apache service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
      become: yes

    - name: Create a basic Black Friday Landing Page
      ansible.builtin.copy:
        content: "<h1>Black Friday is Live!</h1><p>Server: {{ ansible_hostname }}</p>"
        dest: /var/www/html/index.html
      become: yes
